window.VERA_VOICE = {
 "Splendid. Five questions, and I shall build your map as you answer.": "voice/intro.mp3",
 "First — what shall I call you?": "voice/q1.mp3",
 "What do you do for work?": "voice/q2.mp3",
 "What project is on your mind lately?": "voice/q3.mp3",
 "Something you’re learning, or curious about?": "voice/q4.mp3",
 "And how do you recharge?": "voice/q5.mp3",
 "A pleasure. Do go on.": "voice/a1.mp3",
 "A noble trade — filed.": "voice/a2.mp3",
 "On the map, linked to your work.": "voice/a3.mp3",
 "Curiosity suits you.": "voice/a4.mp3",
 "Essential maintenance — noted.": "voice/a5.mp3",
 "Last one — how are you actually doing today?": "voice/q6.mp3",
 "Noted — and thank you for telling me the truth.": "voice/a6.mp3",
 "Welcome back. Before anything else — how are you, really?": "voice/checkin.mp3",
 "And there it is — the Seed of your second brain, planted as we spoke. It lives in this browser — and only this browser — and it will remember you when you return. The production system grows one of these from every conversation… and never forgets.": "voice/finale3.mp3",
 "Three items, sir: the client proposal, a suspiciously empty calendar, and your ongoing refusal to take lunch.": "voice/reel1.mp3",
 "On the wires now, sir — the short answer: three contenders, one clear value pick. Card’s on your display.": "voice/reel2.mp3",
 "The live brain isn't connected on this deployment yet — you're watching the rehearsal. Do try the Brain Map, though: that part is fully live, and I build yours as we talk.": "voice/canned2.mp3",
 "Now — allow me to show off. I shall build you a live operations hub from nothing.": "voice/hub0.mp3",
 "First: a market feed. Live numbers, straight off the wire.": "voice/hub1.mp3",
 "Now the scoreboard — today’s games, as they happen.": "voice/hub2.mp3",
 "A vitals monitor, because one must look after one’s principal.": "voice/hub3.mp3",
 "And there it is — a working hub, assembled from scratch while we spoke. Say my name, and I shall build one for you.": "voice/hub4.mp3",
 "The stage is yours. Say my name, or simply type — and we shall build something of your own.": "voice/stage.mp3",
 "First, let's get acquainted — introduce yourself, and watch me grow your second brain, live.": "voice/tour.mp3",
 "Voice enabled. Lovely to be heard.": "voice/soundon.mp3",
 "Yes?": "voice/wake.mp3",
 "Welcome. I'm Vera — say my name any time you need me.": "voice/welcome.mp3",
 "You have rather exhausted my public allowance for the moment — do return later, or contact the management for the full experience.": "voice/ratelimit.mp3",
 "A gremlin in the wires. Do try again.": "voice/gremlin.mp3",
 "The uplink hiccuped. Once more, if you please.": "voice/uplink.mp3",
 "Welcome back.": "voice/bootwelcome.mp3",
 "Markets, tracked while you sleep.": "voice/bootm1.mp3",
 "Scores, the moment they change.": "voice/bootm2.mp3",
 "Vitals, watched with care.": "voice/bootm3.mp3",
 "Reminders, research — and a guardian’s eye on every scam.": "voice/bootm4.mp3",
 "Are you ready to save the world?": "voice/bootdrop.mp3",
 "Before anything else — how are you, really?": "voice/checkin2.mp3"
};
